# Generated by Django 4.2.6 on 2023-10-15 21:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimmind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backupMegaAcc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='folderName',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='quota',
            field=models.DecimalField(decimal_places=2, default=1024.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userrecords',
            name='media',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[''], size=None),
        ),
    ]
