# Generated by Django 4.2.6 on 2023-10-15 21:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimmind', '0002_user_backupmegaacc_user_foldername_user_quota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecords',
            name='media',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
