# Generated by Django 4.2.6 on 2023-10-15 21:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimmind', '0003_alter_userrecords_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecords',
            name='media',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
