# Generated by Django 4.2.6 on 2023-10-16 02:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimmind', '0004_alter_userrecords_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='backupMegaAcc',
            field=models.TextField(default='kondashivaradhan007@gmail.com'),
        ),
        migrations.AlterField(
            model_name='userrecords',
            name='media',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=''), null=True, size=None),
        ),
    ]
